name: hive_model
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
