name: diarlies
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.7.2
  flutter: 3.29.3
description: A diary app with LLM
dependencies:
  api:
    path: api
  hive_model:
    path: hive_model
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_sign_in: ^6.3.0
  logger: ^2.5.0
  riverpod_annotation: ^2.6.1
  sign_in_with_apple: ^7.0.1
  slang: ^4.7.2
  slang_flutter: ^4.7.0
  flutter_svg: ^2.1.0
  photo_manager: ^3.7.1
  permission_handler: ^12.0.0+1
  location: ^8.0.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.12.2
  shared_preferences: ^2.5.3
  geolocator: ^14.0.1
  flutter_background_service: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.2.1
  path_provider: ^2.1.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  built_collection: ^5.1.1
  mime: ^2.0.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  built_value: ^8.9.5
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.6.5
  slang_build_runner: ^4.7.0
dependency_overrides:
  source_gen: ^2.0.0
  analyzer: ^7.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-VariableFont_wght.ttf
    - family: LexendGiga
      fonts:
        - asset: assets/fonts/LexendGiga-VariableFont_wght.ttf
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-VariableFont_wght.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-VariableFont_wght.ttf
    - family: ZenKurenaido
      fonts:
        - asset: assets/fonts/ZenKurenaido-Regular.ttf
