name: diarlies
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.7.2
  flutter: 3.29.3
description: A diary app with LLM
dependencies:
  api:
    path: api
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  riverpod_annotation: ^2.6.1
dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.6.5
flutter:
  uses-material-design: true
  assets:
    - assets/images/
