name: CI (mobile)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
      - '.github/workflows/ci-mobile.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'mobile/**'
      - '.github/workflows/ci-mobile.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - name: Install flutter
        uses: ./.github/actions/install-flutter
        with:
          working-directory: mobile
      - name: Analyze
        run: dart analyze . --no-fatal-warnings
      - name: Format
        run: chmod +x .scripts/format.sh && ./.scripts/format.sh
      - name: Test
        run: flutter test
  build-android:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - name: Install flutter
        uses: ./.github/actions/install-flutter
        with:
          working-directory: mobile
#      - name: Generating debug keystore and SHA1 key
#        shell: bash
#        run: |
#          keytool -keystore ${{ github.workspace }}/debug.keystore \
#          -J-Dkeystore.pkcs12.legacy -genkey -v -keyalg RSA -validity 10950 \
#          -storepass android -keypass android -alias androiddebugkey \
#          -dname "CN=Android Debug, O=Android, C=US"
#      - name: Prepare Debug key.properties
#        shell: bash
#        run: |
#          echo "storePassword=android" > ${{ github.workspace }}/mobile/android/key.properties
#          echo "keyPassword=android" >> ${{ github.workspace }}/mobile/android/key.properties
#          echo "keyAlias=androiddebugkey" >> ${{ github.workspace }}/mobile/android/key.properties
#          echo "storeFile=${{ github.workspace }}/debug.keystore" >> ${{ github.workspace }}/mobile/android/key.properties
      - name: Run cicd_pre_build.sh
        run: (cd .scripts && bash cicd_pre_build.sh)
      - name: Build App Bundle
        run: flutter build appbundle --debug --dart-define-from-file=dart_defines/.env.prod
  build-ios:
    timeout-minutes: 15
    runs-on: macos-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - name: Install flutter
        uses: ./.github/actions/install-flutter
        with:
          working-directory: mobile
      - name: Run cicd_pre_build.sh
        run: (cd .scripts && bash cicd_pre_build.sh)
      - name: Build iOS
        run: flutter build ios --release --no-codesign --dart-define-from-file=dart_defines/.env.prod
