name: Discord PR Notification

on:
  pull_request:
    types: [opened] # プルリクエストが 'opened' (作成された) 状態になった時のみトリガー

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            新しいプルリクエストが作成されました:tada:
            **タイトル:** ${{ github.event.pull_request.title }}
            **作成者:** ${{ github.event.pull_request.user.login }}
            **URL:** ${{ github.event.pull_request.html_url }}
